title: Anand Bait
subtitle: Ruby on Rails Developer & Technophile
description: >- # this means to ignore newlines until "baseurl:"
  I'm a Ruby on Rails Developer with over a decade of experience

url: "https://anandbait.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Shop
    url : /shop
  - text: Contact
    url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: anand-profile.jpeg
author: Anand Bait
author_bio: Hi, my name is Anand Bait. I'm a Ruby on Rails Developer with over a decade of experience.
author_email: "anand.bait@gmail.com"
author_location: India
author_website_url: "https://anandbait.github.io"
typewrite-text: I'm a Ruby on Rails Developer with over a decade of experience.
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
  - company_name: Allerin
    company_logo: allerin.png
    company_url: https://allerin.com
    designation: Member of Technical Staff
    description: Worked on projects from various domains like fintech, social media, CMS, HRMS, etc.
    visibility: true
  - company_name: Webonise
    company_logo: webonise.jpeg
    company_url: https://webonise.com
    designation: Senior Software Developer
    description: Worked on Ruby on Rails project
    visibility: true
  - company_name: Tata Consultancy Services (TCS)
    company_logo: tcs.png
    company_url: https://tcs.com
    designation: IT Analyst
    description: Worked on various Ruby on Rails projects for a client
    visibility: true
  - company_name: MSCI (Morgan Stanley Capital International)
    company_logo: msci.png
    company_url: https://msci.com
    designation: Associate (Ruby on Rails Developer)
    description: Worked on product
    visibility: true
  - company_name: Coupa Software
    company_logo: coupa.png
    company_url: https://coupa.com
    designation: Senior Software Engineer
    description: Worked on Ruby on Rails product
    visibility: true
  - company_name: Agnos Inc
    company_logo: agnos.png
    company_url: https://agnos.io
    designation: Technical Lead
    description: Worked on Ruby on Rails product
    visibility: true

# Education
author_education_details:
  - college_logo: atharva.jpeg
    college_name: Atharva College Of Engineering
    college_url: https://atharvacoe.ac.in/
    college_degree: B.E. (Computers)
    description: Bachelor of Engineering (Computers)
    visibility: true

# Projects
author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://hack4r.com
    visibility: true

# social links
twitter_username: anand_bait
github_username:  anandbait
facebook_username: anandbait
linkedin_username: anandbait
#behance_username: johndoe
instagram_username: pixonic.anand
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: anandbait

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
#formspree_email: johndoe@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: anandbait
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      summary: ""
      author: anandbait
      date: '2023-02-28 1:35:23 +0530'
      category: []
      tags: []
      keywords: ""
      thumbnail: /assets/img/img-not-available.png
      usemathjax: false
      permalink: /blog/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
